package org.tharrisx.util.text;

import org.tharrisx.util.RandomGeneratorUtils;

/**
 * Provides generatation of Lorem Ipsum paragraphs.
 * @author tharrisx
 * @version 1.0.0
 * @since 1.0.0
 */
public final class LoremIpsumGenerator {

  public static String generate(int numParagraphs) {
    StringBuffer retBuf = new StringBuffer(512);
    for(int cv = 0; cv < numParagraphs; cv++) {
      retBuf.append(randomParagraph());
    }
    return retBuf.toString();
  }

  public static int randomInt(int numParagraphsLow, int numParagraphsHigh) {
    return RandomGeneratorUtils.randomInt(numParagraphsLow, numParagraphsHigh);
  }

  private static String randomParagraph() {
    return LOREM_IPSUMS[RandomGeneratorUtils.nextInt(LOREM_IPSUMS.length)];
  }

  private static final String[] LOREM_IPSUMS = {
      "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit lobortis nunc. Nullam felis. Maecenas varius sapien vitae quam. Etiam vitae erat. Ut ipsum purus, sollicitudin a, eleifend vitae, laoreet a, nisi. Nullam pharetra. Vivamus dignissim, nulla nec mollis tincidunt, pede felis imperdiet quam, nec gravida nisi sapien et turpis. Integer id mauris quis augue molestie laoreet. Praesent suscipit. Suspendisse a orci. Quisque arcu nunc, pellentesque eget, vestibulum non, volutpat id, diam. Suspendisse potenti. Cras sapien orci, suscipit non, varius quis, placerat eu, tortor. Suspendisse ut enim id tortor egestas tristique. Cras iaculis nisi id nibh. Vivamus gravida lorem sit amet dolor. Pellentesque eu lorem.</p>",
      "<p>Ut nec odio ullamcorper nibh dignissim elementum. Integer arcu. Morbi augue libero, nonummy in, rutrum ut, dignissim id, nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rhoncus felis et elit. Mauris faucibus sem vitae massa. Duis eget velit sit amet nunc porttitor blandit. Sed a nulla. Praesent nunc. Maecenas lorem odio, adipiscing fringilla, vestibulum quis, ullamcorper non, nisl. In lobortis sapien sed nisl lacinia sollicitudin. Nam iaculis dolor non velit. Praesent rutrum pulvinar ante. Suspendisse potenti. Etiam leo nibh, suscipit sed, dignissim sed, dictum vitae, velit. Mauris vel sapien. Vestibulum eget massa.</p>",
      "<p>Duis eros nunc, ornare a, sagittis id, molestie ac, ante. Proin auctor mi non lacus. Phasellus dapibus. Nullam id urna in arcu malesuada imperdiet. Praesent ut elit. Mauris fermentum tortor. Integer tincidunt ullamcorper neque. Ut elit pede, imperdiet non, tempor sit amet, ullamcorper eget, mauris. Phasellus egestas. Nam suscipit urna in est. Vivamus semper sem quis orci. Quisque hendrerit, lacus quis vehicula congue, sapien elit iaculis diam, a consectetuer augue diam non risus. Curabitur a eros. Curabitur faucibus. Quisque orci diam, elementum quis, porttitor quis, mollis vel, sem.</p>",
      "<p>Curabitur non nibh id mi pellentesque vestibulum. Etiam elit. Proin at libero. Nunc mattis arcu sed ligula. Morbi nec arcu vitae nisl rutrum ultrices. Quisque id ligula eu pede congue tempor. Aenean molestie consectetuer justo. Phasellus vel mi. Donec ultrices porta pede. Pellentesque commodo consectetuer libero. Praesent est mi, scelerisque eget, mattis nec, pellentesque pulvinar, neque. Vestibulum tortor enim, fermentum non, pulvinar id, commodo ut, urna. Sed commodo luctus purus.</p>",
      "<p>Duis turpis. Quisque vitae nulla. Fusce imperdiet nisl quis magna. Suspendisse arcu nunc, bibendum nec, blandit at, rhoncus eu, ligula. Praesent euismod sem nec dui. Vestibulum tristique convallis dui. Praesent at quam quis mauris sodales rhoncus. Suspendisse ac nunc. Etiam ut dui. Praesent luctus venenatis magna. Curabitur aliquet, ligula et faucibus consectetuer, pede elit faucibus erat, ac convallis quam tortor ut ligula. Fusce ut dolor ac arcu rhoncus fermentum. Suspendisse nonummy nulla sit amet enim dictum egestas. Aliquam erat volutpat.</p>",
      "<p>Nunc sapien pede, ultrices ac, aliquet sit amet, laoreet vel, nibh. Aliquam malesuada urna sit amet augue. Suspendisse potenti. Ut rutrum dignissim neque. Morbi sed turpis eu est iaculis blandit. Sed risus nisl, sollicitudin vitae, lobortis in, dictum blandit, velit. Morbi rutrum ligula eu dui. Sed molestie nibh. Quisque in dui id odio commodo fringilla. Duis ipsum ligula, placerat at, dapibus ac, molestie et, felis.</p>",
      "<p>Aenean ultricies urna quis dolor. Vivamus enim odio, tristique quis, elementum nec, egestas nec, mi. Mauris mi tortor, gravida vitae, mollis vitae, auctor sit amet, neque. Duis sit amet est in odio tincidunt rhoncus. Curabitur porttitor libero. Nullam dapibus commodo tortor. Quisque nec felis. In hac habitasse platea dictumst. Praesent laoreet. Praesent at nisl.</p>",
      "<p>Fusce elementum. Fusce non lacus. Phasellus id mauris a metus auctor varius. Ut lacinia tortor sit amet urna. Vestibulum et pede malesuada orci blandit iaculis. Aliquam et ipsum. Duis nec urna eu augue condimentum ornare. Curabitur commodo, pede eu placerat condimentum, magna purus rutrum leo, eget euismod lectus lectus non nunc. Mauris molestie malesuada eros. Proin quis lorem at lacus viverra tincidunt. Vestibulum nibh tellus, pretium eget, laoreet et, facilisis nec, tellus. Donec id sem et sapien mattis malesuada. Morbi mi. Morbi dolor lorem, nonummy quis, bibendum sit amet, eleifend non, justo.</p>",
      "<p>Nulla convallis semper est. Fusce aliquam congue justo. Proin ut leo eu nunc convallis imperdiet. Phasellus gravida, orci sed gravida sollicitudin, libero ipsum mollis dolor, tristique imperdiet lectus nulla at tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque nec neque. Proin dolor justo, facilisis vel, suscipit nec, fermentum in, mi. Vestibulum dui eros, congue ultrices, dictum et, viverra et, risus. Etiam et erat ut sapien pharetra cursus. Fusce erat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed luctus nisi in lectus. Suspendisse mauris felis, facilisis vel, posuere sit amet, feugiat a, est. Vivamus dapibus. Nulla ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce eget lacus.</p>",
      "<p>Praesent condimentum nunc in ante. Sed posuere eros sit amet erat tempor porta. Cras sollicitudin eleifend purus. In hac habitasse platea dictumst. In porta justo quis nisi. Nam non ligula a quam viverra rhoncus. Aenean nisl sem, accumsan in, molestie nec, aliquam in, ligula. Proin tempor lacus nec neque. In aliquam. Duis dictum semper tortor. Nam pulvinar, dolor vel suscipit tincidunt, magna eros blandit libero, nec malesuada arcu sapien nec dolor. Ut faucibus nunc volutpat diam. Nullam at sapien. Fusce et mauris. Quisque accumsan, nunc sit amet faucibus condimentum, pede nisi vulputate est, non vestibulum urna nibh vel eros. Fusce ac tellus non lacus iaculis dignissim. Mauris a orci at elit hendrerit mattis. Integer vitae ipsum. Proin ultrices ullamcorper magna. Phasellus vitae massa.</p>",
      "<p>Duis tristique elit quis diam. Curabitur non nibh. Duis cursus faucibus arcu. Vestibulum sodales, enim ac aliquam accumsan, ante augue dapibus erat, vitae hendrerit est libero et nisl. Cras congue ipsum eget erat. Fusce gravida. Quisque gravida eros venenatis leo. Donec nonummy dapibus nisl. Praesent fermentum augue id augue. Morbi gravida metus non nibh. Vestibulum placerat enim eu mi. Nunc molestie ante vitae massa. Nulla facilisi.</p>",
      "<p>Aliquam id mi eu neque sollicitudin venenatis. Maecenas lacinia ante a sem. Proin bibendum ipsum ut diam. Suspendisse ornare. Nulla pede. Sed nulla. Sed sollicitudin quam non turpis. Praesent felis nisi, dapibus id, placerat tincidunt, aliquet quis, lorem. Sed ligula. Sed ullamcorper. Pellentesque nec ipsum pharetra magna dapibus nonummy.</p>",
      "<p>In vel orci. Cras odio. Vestibulum commodo leo ut tellus. Curabitur nec nibh. Duis lacinia. Mauris gravida eleifend urna. In nisi nunc, pellentesque nec, porta congue, fringilla at, urna. Aenean quis mauris sit amet eros eleifend vulputate. Nulla a mi. Praesent et pede. Nunc id dui eget tortor iaculis commodo.</p>",
      "<p>Etiam ut arcu. Nulla adipiscing metus ac felis. In urna metus, congue eget, mollis nec, interdum vel, enim. Nam a magna. Vivamus metus. Duis elementum leo at nisl. Suspendisse nunc nisi, ornare sit amet, mollis vitae, convallis vitae, turpis. In in lorem et lorem condimentum blandit. Nulla eu enim. Vestibulum blandit pharetra enim. Suspendisse dictum porttitor orci.</p>",
      "<p>Sed sagittis auctor metus. Nunc euismod neque non dui. Morbi vel arcu. Duis lobortis varius est. Aliquam quis enim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consequat. Curabitur porta sagittis leo. Nullam id mauris. Fusce ut dolor vel dolor congue venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Aenean ut quam. Ut lectus magna, vehicula et, dapibus in, luctus eu, nisl.</p>",
      "<p>Nunc leo. Etiam tortor. Suspendisse potenti. Nam non magna eu nibh suscipit dictum. Pellentesque elit nulla, interdum id, hendrerit eget, tincidunt eu, lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla eget quam id pede imperdiet semper. Nam laoreet odio ut lorem. Vivamus quis nisi sit amet est lacinia rhoncus. Nunc eget libero in ipsum varius nonummy. Vestibulum ac sem. Sed imperdiet ipsum eget nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus magna orci, pulvinar non, tincidunt sit amet, feugiat sed, sapien.</p>",
      "<p>Aenean gravida mi nec dui. Aenean pede sem, iaculis feugiat, volutpat quis, egestas ut, erat. Integer tincidunt. Fusce enim. Sed mattis laoreet velit. Morbi dignissim scelerisque purus. Curabitur ac tortor. Fusce elementum tempus massa. Cras at urna eget nisl bibendum luctus. Duis ligula ante, faucibus sit amet, tempor vitae, facilisis sit amet, tellus. Pellentesque eget enim.</p>",
      "<p>Integer lacus tortor, lacinia nec, tempus in, eleifend et, ligula. Fusce dolor ligula, cursus nec, interdum in, facilisis sed, magna. Donec ullamcorper luctus dolor. Duis metus. Maecenas nonummy sollicitudin sapien. Quisque lacinia. Donec hendrerit mi eget urna tincidunt convallis. Vivamus elementum eros at enim. Proin laoreet vestibulum tortor. Praesent pretium lectus vitae felis. Fusce blandit leo. In posuere nisi non odio. Sed sollicitudin nulla id ligula. Proin quis purus.</p>",
      "<p>Vivamus tincidunt dictum orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et dolor ac erat convallis sollicitudin. Donec et ipsum. Nullam tincidunt, velit vitae aliquam commodo, elit dui adipiscing est, sed viverra quam diam quis libero. Sed ultricies nisi eget elit. Aliquam neque nibh, aliquam id, porta a, ullamcorper et, libero. Aenean libero lectus, sagittis in, blandit nec, rhoncus et, pede. In lobortis euismod nisi. Ut in purus. Vivamus nibh. Vivamus dolor nulla, venenatis bibendum, aliquet ut, nonummy eu, ipsum. Nam quis erat et nibh cursus faucibus. Vestibulum nec urna.</p>",
      "<p>Aliquam eget nulla congue nibh semper laoreet. Cras in orci. Nunc hendrerit sapien vitae tortor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus sagittis, diam eu fermentum suscipit, sem magna iaculis sem, in sodales lacus lorem sit amet elit. Maecenas ante. Sed blandit, turpis at tincidunt lacinia, metus augue malesuada nisi, eu vulputate lectus nulla a justo. Praesent mollis fermentum nibh. Cras non massa. Mauris fermentum. Donec ultrices erat id nibh. Nulla facilisi. Vivamus ornare purus vitae sapien ultricies consectetuer. Duis orci ipsum, pellentesque nec, congue a, iaculis ac, neque. Vivamus malesuada rutrum metus. Nunc mollis. Etiam semper tortor luctus augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Ut volutpat purus.</p>",
      "<p>Suspendisse porta pellentesque lacus. Vestibulum enim magna, laoreet ut, bibendum nec, posuere sed, magna. Maecenas laoreet. In nibh. Pellentesque ullamcorper fringilla ipsum. Aliquam orci. Sed malesuada tristique leo. Nam fermentum. Maecenas elementum felis ut diam. Proin tincidunt fermentum metus. Praesent non felis. Etiam sed arcu. Integer in pede vel turpis porttitor pulvinar. Nunc consectetuer, pede quis luctus fringilla, mi sem congue nibh, in pharetra est pede non diam. Vestibulum tempor eleifend metus. Maecenas venenatis orci id dolor. Aenean molestie lacinia mauris. Mauris ornare ipsum vitae sem. Mauris vel enim et mauris pretium molestie. Ut magna pede, condimentum quis, sollicitudin vitae, pellentesque in, sapien.</p>",
      "<p>Mauris eu diam et risus scelerisque ornare. Quisque varius libero et mauris mollis dapibus. Aliquam erat volutpat. Proin et lectus in diam egestas posuere. Morbi nibh. Ut euismod rhoncus mauris. Maecenas adipiscing, nisl at mollis vulputate, lorem sapien porta risus, a auctor urna lectus eu enim. Vivamus sed sapien. Aliquam scelerisque ante id quam. Curabitur vel urna. Integer sagittis quam non velit. Vestibulum tortor. Curabitur posuere enim et nisl.</p>",
      "<p>Nam faucibus nibh vitae nisl. Cras euismod, ligula a rutrum nonummy, ipsum mauris luctus eros, id malesuada nisi metus sit amet lacus. Donec interdum tempus magna. Quisque quis nunc non massa elementum volutpat. Fusce in ligula. Integer ut erat. Nam rhoncus enim in mauris. In fringilla porttitor elit. Nulla dictum adipiscing odio. Nunc velit sapien, interdum nec, pellentesque eu, luctus id, tellus. Integer congue adipiscing velit. Sed cursus sapien vitae urna. Proin eget magna. Donec cursus. Suspendisse risus. Aenean elementum tempus lorem.</p>",
      "<p>Quisque mollis urna at lorem. Nunc in metus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam sit amet quam in metus lobortis laoreet. Ut id nisi in risus porta imperdiet. Nam blandit turpis eu augue. Donec posuere fermentum nulla. Aenean consectetuer, odio sit amet convallis rhoncus, ipsum pede egestas odio, ut posuere ipsum erat lobortis massa. Curabitur in nulla id nisi vestibulum tempus. Nam quis augue id erat lobortis viverra. Curabitur urna turpis, elementum commodo, porta sit amet, condimentum et, nisi. Nullam nec mauris sed justo suscipit venenatis. Aliquam porttitor nunc in pede. Morbi eros. Integer eu quam in odio aliquam blandit. Aliquam erat volutpat. Mauris eget dui non est lacinia placerat. Integer id urna.</p>",
      "<p>Nullam nibh orci, egestas vitae, fermentum ut, pulvinar a, magna. Quisque lobortis ligula non tortor blandit porta. Etiam purus. Maecenas a orci. Aenean pellentesque. Integer varius ullamcorper libero. Integer convallis rhoncus ante. Nullam tortor augue, condimentum ut, pulvinar eget, eleifend nec, odio. Donec nisl justo, blandit eu, rhoncus id, ullamcorper quis, mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent auctor, neque in accumsan luctus, erat augue pellentesque mauris, ut ullamcorper ante neque eu ipsum.</p>",
      "<p>Suspendisse rutrum. Proin nisl massa, suscipit eget, luctus at, pretium ut, purus. Suspendisse ac metus at ipsum posuere ullamcorper. Etiam commodo. Aenean scelerisque commodo turpis. Phasellus tincidunt, ante vitae malesuada scelerisque, urna purus tincidunt mi, a elementum sapien felis ut orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ut ligula varius risus pulvinar condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla interdum hendrerit nisl. Aenean nibh. Sed blandit eros eu odio. Curabitur facilisis semper ante. Curabitur suscipit nisl ut nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec in nisi. Ut vel lorem ac magna hendrerit placerat. Praesent porta eros ac turpis. Nam at ante. Nam libero.</p>",
      "<p>Vivamus leo nibh, posuere vel, pulvinar non, pellentesque a, augue. Quisque at massa sit amet quam porta egestas. Praesent egestas, neque at vestibulum gravida, leo lorem condimentum turpis, vel interdum diam purus ut erat. Quisque aliquam dui vitae leo. In vehicula fringilla ipsum. Morbi sagittis laoreet elit. Etiam adipiscing tempus odio. Quisque luctus varius diam. Duis aliquet, sem eget pellentesque porttitor, ante risus ornare est, nec ultrices erat leo nec eros. Integer libero. Curabitur pellentesque. Vivamus sed quam. Aenean ac metus. Ut imperdiet. Morbi id risus. Pellentesque ut leo. Duis sit amet lectus quis mauris blandit iaculis. Aliquam erat volutpat. Pellentesque tellus. Suspendisse potenti.</p>",
      "<p>Nam augue odio, faucibus vehicula, cursus nec, mollis vitae, erat. Nulla facilisi. Vestibulum imperdiet ante non velit. Donec dictum. Integer et mi non urna fermentum rutrum. Sed posuere dictum lorem. Nam diam est, consequat vel, auctor vel, nonummy et, ipsum. Curabitur vel neque quis lectus porta laoreet. Integer tincidunt purus ac nulla. Curabitur aliquet consequat dolor. Donec nec metus at ligula feugiat consequat. Nulla dui orci, pulvinar sit amet, nonummy ac, porttitor vel, ante. Etiam tristique malesuada nulla. Curabitur nulla augue, vestibulum vitae, pretium sed, dictum eu, libero.</p>",
      "<p>Proin dapibus, risus nec luctus scelerisque, lacus pede tristique urna, sit amet ultricies lectus tellus at justo. Proin sed nunc. Nulla lacinia leo. Ut euismod, ligula vel condimentum eleifend, justo ante venenatis orci, dapibus mollis lorem tortor vitae diam. Vivamus quis massa at purus molestie rhoncus. Duis erat elit, egestas at, luctus in, pulvinar et, dui. Pellentesque nec lorem vitae elit sodales facilisis. Nunc tincidunt, dolor non feugiat volutpat, nunc dui tristique diam, in congue purus neque sed tortor. Donec est. Integer risus. Duis a nunc. Praesent enim. Nunc et diam bibendum justo aliquam consectetuer. Suspendisse potenti. Integer mollis. Pellentesque semper ipsum blandit sapien. Suspendisse potenti. Cras sed mi vel pede facilisis sollicitudin. Vivamus facilisis aliquet lorem. Cras faucibus.</p>",
      "<p>Sed felis. Donec aliquet nibh sed massa. Vivamus elementum pede et augue. Sed aliquet dignissim pede. Praesent erat dolor, euismod in, lobortis quis, adipiscing nec, sapien. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin ut diam. Donec venenatis arcu sit amet enim. Duis semper porta sem. Cras nec dolor suscipit dui pellentesque tincidunt. Morbi id nunc nec nisl sagittis pharetra. Praesent urna felis, egestas vel, porttitor sit amet, feugiat vitae, nulla. Phasellus venenatis interdum est. Nunc et erat ac libero elementum fringilla. Pellentesque elementum arcu nec leo. Cras ullamcorper aliquam arcu. Nam in purus et arcu luctus condimentum.</p>",
      "<p>Vivamus ante dui, interdum quis, dignissim in, varius non, metus. Aliquam posuere. Mauris vulputate magna et arcu. Integer neque ante, hendrerit nec, posuere ac, condimentum posuere, eros. Vivamus tempor, nibh in mollis scelerisque, mi sem gravida ligula, vitae consequat dolor pede sed enim. Curabitur lectus neque, accumsan auctor, commodo nec, scelerisque ut, nulla. In diam mauris, faucibus ac, malesuada at, molestie vitae, erat. Phasellus a tortor laoreet turpis viverra nonummy. Nunc nec purus vel lorem pharetra vulputate. Vestibulum sed ante vel arcu sagittis tempor. Maecenas vel massa quis ante facilisis egestas.</p>",
      "<p>Sed elit augue, fringilla sit amet, aliquet at, adipiscing vitae, mi. Nullam justo felis, facilisis vitae, iaculis in, vehicula ac, felis. Nullam ut eros vel lacus volutpat consectetuer. Curabitur aliquam urna ut lorem. Donec vitae nisl. Aliquam rutrum risus sit amet tortor. Ut neque nisl, laoreet eget, vehicula nec, vulputate in, dui. Mauris pellentesque. Suspendisse mollis, odio nec ullamcorper dictum, quam lectus nonummy nibh, eu nonummy urna metus sit amet tellus. Fusce ligula pede, porta ac, tempus ac, lacinia a, arcu. Nullam a elit. Vestibulum libero turpis, suscipit sed, fringilla eu, faucibus nec, dolor. Duis malesuada tincidunt libero. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam mi urna, convallis eu, aliquet quis, vehicula quis, nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras suscipit sapien non sapien. Nam quis massa in pede mattis ornare. Nam massa arcu, euismod eget, ultricies eget, mollis sed, magna.</p>",
      "<p>Cras egestas urna eget massa. Praesent ullamcorper eros. Proin sed leo. Sed nisi nisl, viverra id, commodo vel, gravida quis, risus. Sed eu dolor. Suspendisse libero. Praesent gravida tellus vitae nibh. Ut eu arcu. Quisque bibendum elit. Suspendisse potenti. Nullam elementum malesuada enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed vestibulum odio id turpis. Nunc neque quam, semper ac, lobortis et, adipiscing a, erat. Nulla nulla. Ut molestie, diam nec dignissim pretium, urna tellus malesuada nisl, quis lobortis eros lectus euismod odio. Cras neque. Vivamus suscipit, arcu quis interdum tristique, sem nisi hendrerit ligula, in rutrum turpis urna in pede. Ut ac risus. Suspendisse potenti.</p>",
      "<p>Nulla tincidunt, urna dictum posuere sodales, urna velit congue metus, non hendrerit tellus est tincidunt nulla. Nullam blandit. Nulla tincidunt nibh id nisl. Duis consectetuer luctus arcu. Pellentesque sit amet leo ut mauris consequat sagittis. Curabitur scelerisque. Nunc in nibh. Phasellus rutrum dui nec ante. Nunc eget sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut in libero. Praesent et pede.</p>",
      "<p>Phasellus rhoncus risus eu augue. Duis aliquet, augue at placerat fringilla, erat magna aliquam libero, tincidunt eleifend mi purus sed quam. Sed dui tellus, consequat ac, faucibus ut, vestibulum eget, neque. Vivamus vel odio. Praesent lacinia, quam a malesuada viverra, sem orci imperdiet augue, non tincidunt nunc orci id felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ac mi. Fusce ante. Etiam lacinia placerat nulla. Curabitur tincidunt enim ut libero. Suspendisse pulvinar. Vestibulum lacus lacus, suscipit ut, tempus sit amet, eleifend nec, mauris. Pellentesque pharetra quam vel ligula. Curabitur ac purus in justo condimentum consectetuer. Morbi sagittis semper velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>",
      "<p>Vivamus posuere nulla sed orci. Proin lectus mi, pharetra ut, condimentum ut, accumsan ut, ante. Sed massa. Maecenas pretium augue ut ligula. Curabitur enim arcu, nonummy ac, feugiat nec, pharetra in, neque. Mauris erat lorem, dapibus et, vehicula et, varius vel, lacus. Sed sapien lorem, interdum ut, faucibus non, rhoncus vitae, pede. Maecenas est nunc, hendrerit vitae, scelerisque eu, eleifend at, velit. Sed ultrices eros et elit. Praesent id augue non massa dapibus congue. Morbi eleifend placerat ante. Fusce euismod, orci in tristique rhoncus, nibh nulla convallis elit, pretium facilisis ante massa varius nunc. Nullam quis risus.</p>",
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus lacinia viverra mi. Integer semper sem eleifend libero. Nullam tellus. Nunc elit. Sed volutpat metus in augue adipiscing volutpat. Vivamus dignissim, eros a vulputate laoreet, felis neque mollis nibh, nec mattis leo ipsum sit amet dui. Nunc volutpat feugiat lacus. Morbi interdum rhoncus dolor. Aenean nisl libero, mattis cursus, egestas eu, aliquam ut, quam.</p>",
      "<p>Maecenas elit magna, hendrerit in, interdum vitae, suscipit at, sem. Nam pretium justo ut sapien. Sed mattis arcu nec nibh. Nam molestie metus non mi. Donec urna. Nunc libero. Curabitur pulvinar mi non diam. Nullam aliquam tristique lectus. Nam enim quam, ultrices et, nonummy et, vehicula eget, ligula. Nunc lacinia dictum nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec quis nunc et nisi adipiscing rhoncus. Proin vitae mauris. Curabitur fermentum venenatis est. Proin hendrerit ligula nec risus. Sed ut enim sit amet justo aliquam convallis. Vivamus sit amet enim vel enim tincidunt aliquam. Mauris a erat at turpis ultricies dictum. Nam odio. Morbi a leo non diam sodales congue.</p>",
      "<p>Vivamus faucibus condimentum nisi. Fusce ullamcorper urna at nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquet sapien eget dolor. Duis euismod sapien id sapien. Suspendisse nec neque consectetuer tortor sodales gravida. Maecenas dapibus ipsum. Nunc feugiat mollis nisl. Morbi iaculis nisl ac metus. Vestibulum porttitor massa sit amet est. Aenean sit amet ante. Quisque eu dolor ac lectus posuere dapibus.</p>",
      "<p>Vestibulum eu odio. Nulla sed justo. In tempus dapibus orci. Pellentesque at orci. Nulla at risus sit amet nulla lobortis hendrerit. Fusce varius dapibus nisl. Vestibulum tempus leo et odio rhoncus auctor. In hac habitasse platea dictumst. Donec sed enim quis odio congue aliquet. Mauris eu lorem ut odio vehicula sodales. Mauris at arcu vitae massa faucibus fringilla. Etiam molestie tincidunt sem. Integer tortor est, consequat in, blandit vitae, molestie nec, velit. Nam eleifend pretium urna. Sed nonummy condimentum metus. Nulla sed dolor.</p>",
      "<p>Integer interdum adipiscing justo. Aliquam varius. In hac habitasse platea dictumst. Maecenas venenatis massa eu arcu. Nunc a nulla. Aliquam semper malesuada lectus. Praesent gravida iaculis turpis. Cras sollicitudin. Quisque vitae erat id neque nonummy laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a lectus. Integer non tellus sed purus volutpat vehicula. Praesent eleifend est. Integer rutrum, nunc pharetra eleifend tincidunt, velit massa rhoncus ipsum, sit amet interdum augue enim non est. Nunc eget risus. Mauris sit amet enim. Sed ipsum. Etiam venenatis. In tempus, orci eu consequat faucibus, lectus tortor vestibulum erat, non bibendum arcu leo sed leo. Nam rutrum dictum sem.</p>",
      "<p>Etiam tempor tempus augue. Fusce accumsan justo non ligula. Integer sapien odio, dictum quis, facilisis quis, pharetra sit amet, augue. Sed placerat. In erat. Sed risus. Pellentesque et orci. Ut porttitor dolor. Aenean dignissim nisl dignissim urna tempor mollis. Curabitur semper dolor quis lectus.</p>",
      "<p>Pellentesque tortor lorem, dignissim at, eleifend vitae, pharetra in, lorem. Vivamus arcu risus, gravida a, aliquet quis, accumsan eu, mi. Morbi non risus a quam tincidunt dignissim. Aliquam et est. Sed vehicula. Etiam mattis varius dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc eget arcu. Integer porttitor dolor sit amet ante. Ut euismod nisl accumsan purus. Vestibulum elementum rutrum tortor. Nunc fermentum nisl sit amet urna pretium malesuada. Donec auctor blandit mauris. Curabitur blandit nisl vitae felis scelerisque vehicula. Nulla dictum erat pharetra nisl. Curabitur porttitor ipsum lobortis ipsum eleifend posuere. Phasellus id nunc. Proin nec eros. Ut ac arcu.</p>",
      "<p>Vivamus nec dolor in orci tristique posuere. Nulla pellentesque tellus et dui sodales auctor. Nunc lacinia nisl in turpis. Vestibulum varius. Maecenas lorem ante, pretium ornare, consectetuer nec, imperdiet in, ligula. In egestas elit eu justo. Pellentesque eleifend. Maecenas at lacus. Etiam sit amet tortor sed nisi rhoncus cursus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam non nisi. In id risus. Ut eros. Vivamus aliquam. Duis consectetuer justo ac eros. Aenean laoreet.</p>",
      "<p>Cras consequat feugiat massa. Aenean pharetra, augue eget pretium lacinia, augue orci tempor augue, sit amet posuere turpis nisl eu purus. Proin fermentum mollis urna. Aenean mollis ipsum eget nisl. Curabitur enim nibh, fringilla eu, iaculis at, vestibulum id, augue. Donec velit mauris, elementum ac, lobortis vel, pulvinar ac, velit. Sed metus. Etiam non orci. Etiam nisl dolor, volutpat nec, scelerisque ac, imperdiet et, orci. Aliquam nisi felis, euismod sit amet, fermentum eu, varius sed, velit. Integer turpis. Duis ac est. Integer quis ligula a nisi imperdiet sodales. Integer sagittis scelerisque enim. Nam magna lacus, ultricies id, tincidunt id, bibendum nec, est. Duis porta orci nec arcu hendrerit consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus gravida ultrices leo.</p>",
      "<p>Aliquam sit amet ligula. Aliquam et diam. Proin feugiat mi eget nibh. Integer ut neque. Aenean pharetra dapibus nisl. Curabitur gravida. Ut aliquam, enim vitae pulvinar molestie, sem nibh varius tortor, nec dictum dolor elit fermentum metus. Phasellus ante. Nullam hendrerit dictum arcu. Nunc mollis ante at dolor.</p>",
      "<p>Praesent sit amet risus quis lectus cursus sollicitudin. Curabitur lacinia felis et lectus. Etiam non sapien. Fusce consequat convallis dolor. Maecenas gravida metus non nisi viverra interdum. Sed mattis ante fermentum sem. Curabitur vel dui vitae leo convallis venenatis. Mauris metus sem, ullamcorper in, sollicitudin et, aliquet non, tellus. Nunc blandit neque vitae turpis. Curabitur nec tellus. Quisque ac elit. Cras diam. Donec enim. Vivamus vitae sapien. Proin laoreet est sed eros. Cras eleifend gravida lacus. Sed semper sollicitudin nisl. Aliquam elementum mollis massa. Nam ultrices vehicula pede.</p>",
      "<p>Fusce posuere. Mauris scelerisque tortor sit amet nibh. Vestibulum nulla nisi, viverra et, hendrerit a, egestas malesuada, turpis. Praesent porttitor commodo lectus. Etiam lorem. Maecenas dui leo, tempus eu, nonummy et, pharetra eget, diam. Nulla suscipit ligula vel odio. Pellentesque vitae purus eu velit vulputate semper. Ut lorem pede, consectetuer a, placerat sed, commodo at, nunc. Pellentesque dictum, nunc id convallis convallis, erat augue auctor massa, eu tempus velit orci quis tortor. Maecenas interdum velit eu enim. Etiam orci est, euismod ac, egestas quis, ullamcorper et, est. Quisque elit sapien, convallis sit amet, sagittis at, euismod quis, nisl.</p>",
      "<p>Nunc eget dui. Cras congue adipiscing nulla. Donec blandit ante ac nisl. Ut luctus sem in purus. Donec vulputate. Suspendisse potenti. Maecenas mi urna, venenatis eget, aliquam eu, aliquet et, est. Mauris velit. Donec tincidunt. Duis mollis. Phasellus ornare ante. Nulla arcu risus, viverra a, venenatis vel, pulvinar eleifend, odio. Fusce leo enim, pellentesque eu, varius ut, vulputate consequat, velit.</p>",
      "<p>Curabitur feugiat dolor nec nulla. Duis porttitor, enim sagittis rutrum fringilla, lectus nisl suscipit arcu, quis nonummy velit dolor id enim. Vestibulum viverra erat non augue. Fusce volutpat velit a mi. Praesent velit lacus, tincidunt sit amet, varius sit amet, elementum non, dolor. Vivamus nonummy, massa in pellentesque commodo, diam risus aliquet pede, id auctor mauris eros et justo. Proin nec eros. Nulla viverra. Donec porta augue in dui. Nulla augue. Praesent consequat massa vel ligula. Aliquam erat volutpat.</p>" };

  private LoremIpsumGenerator() {
    // private constructor for utility class
  }
}
